### ISSUE TITLE
Cannot detect response encoding

### ISSUE THREAD

**Issue by pijusn** [wix/wix-http-testkit#45]
I found no way to detect whether response from the server had `Transfer-Encoding: chunked`.

**Comment by noam-almog** [comment]
@pijusn from the current investigation i couldn't find a documentation from akka that it does not expose transfer encoding header.
I spent some time to try to locally reproduce it but couldn't find a way. I do know that akka http will not allow you to set the header and will do that automatically.
can you share some example so that i can reproduce this ?

**Comment by pijusn** [comment]
Previously I found it documented in a different part of documentation but now I found this, more extensive list of _special headers_: https://doc.akka.io/docs/akka-http/10.0.0/java/http/http-model.html#http-headers.

I will send you a link to internal project's branch where I found it.

**Comment by noam-almog** [comment]
resolved
