### ISSUE TITLE
Cannot set custom Host header

### ISSUE THREAD

**Issue by genrym** [wix/wix-http-testkit#64]
When sending a request with an arbitrary _Host_ header - the _Host_ header gets overridden with the value from URL.

Example:
```
get("http://localhost:12345/somePath", but = withHeaders("Host" -> "somehost.com"))
```
The request is sent with _Host_ header = _localhost:12345_ instead of _somehost.com_

**Comment by noam-almog** [comment]
I saw this, without alot of research
https://github.com/akka/akka-http/issues/128
i'll keep this issue open till i have time to figure this out

**Comment by mayboroda** [comment]
@genrym  I had an issue with overriding `Host` header in java and it turns out that there are some security fixes maid in JVM to not allow to override this header. Please read [this](https://stackoverflow.com/questions/7648872/can-i-override-the-host-header-where-using-javas-httpurlconnection-class)

**Comment by genrym** [comment]
@mayboroda Not sure whether this is applicable here. wix-http-testkit uses akka for production code. Only if akka internally uses `HttpUrlConnection`

**Comment by mayboroda** [comment]
@genrym agree, I was assuming that this is a JVM related issue. Sorry, I had a wrong assumption.
